- README.md
Currently, the `config.fish` example in `README` makes base16-shell load even on non-interactive session. That's not desirable as it will cause corruption of `stdout` when `fish` is spawned by eg. some script. Therefore, I've added a conditional which checks if fish is spawned as an interactive shell.
> README: Load base16 only on interactive fish sessions

- colortest
I've created a wrapper `colortest` command that is in my `$PATH` that calls this `colortest` file. This change allows that to happens whilst still allowing the file to be executed via `./colortest`
> Allow colortest to be called from outside the base16 directory

- templates/default.mustache
Applying a fix that was done here: https://github.com/derimagia/base16-builder/commit/93e87d75d908275776cf23bcdd0784d09ddf6c14
I confirmed that this changes colors in tmux w/o causing the bell to ring.
This fixes issue #24
> Fixing template to generate tmux templates that do not us a bell

- profile_helper.sh
I'm a sucker for automation, so I want to add a `source ~/.vimrc_background` to a FocusGained autocommand in vim. However setting the colorscheme unnecessarily causes vim to redraw, which is annoying. I've added a check to see that either a) there hasn't been a colorscheme loaded yet and b) the colorscheme is different that the current before calling `colorscheme`.
> Only set colorscheme in .vimrc_background if necessary

- profile_helper.sh
Many popular zsh plugin management system set default to noclobber to prevent accidental file overwrites, but this cause problem when creating `.vimrc_background`
e.g.
```
% base16_tomorrow-night
_base16:7: file exists: /Users/gogao/.vimrc_background
```
This PR used force clobbering redirect operator `>|` to replace the normal `>`
`>|` is supported by both zsh and bash.
http://zsh.sourceforge.net/Doc/Release/Redirection.html
https://www.gnu.org/software/bash/manual/html_node/Redirections.html#Redirections  (Section 3.6.2)
> force clobbering when creating .vimrc_background

- base16-shell.plugin.zsh
The file is automatically picked up by various ZSH plugin loaders and executed as the README instructions suggest.
Currently, antigen/antibody pick up `profile_helper.sh` but source it directly, which doesn't work.
> Add zsh plugin loader file (for oh-my-zsh, zgen, antigen, etc.)

- colortest
- profile_helper.sh
Needed for OSs without `/bin/bash`, like NixOS. [More info.](https://news.ycombinator.com/item?id=9708908)
> /bin/bash -> /usr/bin/env bash

- scripts/base16-zenburn.sh
When I created Zenburn I missed the `foreground` value and copied the `magenta` instead of the `white`. When I was using this one in my new ArchLinux with URxvt saw this error.
Also I changed the "black" color to a better one (little darker) for the sake of your eyes!
> Fix Zenburn foreground

- profile_helper.fish
- profile_helper.sh
Currently `profile_helper.[sh|fish]` doesn't work properly if placed in a path with special characters like space.
This commit fixes it.
> escape paths properly in profile_helper.[sh|fish]

- profile_helper.fish
`BASE16_THEME` was wrongly set to `base16-NAME` is my previous diff.
This diff corrects it to `NAME`.
> [fish] strip "base16-" from env var `BASE16_THEME`

- templates/default.mustache
Here's a WIP commit to add support for Linux's TTY consoles as discussed in #127.
I've switched from using `printf` template strings to using shell `function`s in order to allow modifications to the parameters (convert to hex, strip "/"s, etc as needed). I've tested my code in bash, zsh, and sh and in the tty console, urxvt, and termite. If someone could also do basic regression tests in fish, iTerm, etc that would be awesome.
Finally, for now, this commit just edits the mustache file. If you could give me a pointer on how to do your build process, I'd be happy to update it with all of the scripts properly modified.
Thanks for all your work, @chriskempson!
> Support Linux TTY console

- profile_helper.sh
With this PR is now possible to add custom hooks in profile helper. Executable scripts placed in $BASE16_SHELL_HOOKS folder will be run when a base16_* theme is used.
This would be very useful if, for example, i want to update my i3wm config every time i change shell theme.
Someone can use this optional feature like this:
- Step  1
In .bashrc
```
...
BASE16_SHELL=$HOME/.config/base16-shell/
BASE16_SHELL_HOOKS=$HOME/.config/base16-shell-hooks/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
...
```
- Step 2
In ~/.config/base16-shell-hooks/  i can now place as many scripts as i want:
```
#!/bin/bash
##notification
notify-send "$BASE16_THEME" "new base16-shell theme!"
...
```
```
#!/bin/bash
##Update some file,,
echo "$BASE16_THEME" > …
```
> Add hooks in profile_helper.sh

- templates/default.mustache
Closes 141 and closes 142 by fixing the default.mustache template. 
To pass an escape sequence through GNU screen it requires ESC P ... ESC \ but Xterm requires ESC ] ... BEL so the correct passthrough is ESC P ESC ] ... BEL ESC \
See https://lists.gnu.org/archive/html/screen-users/2006-05/msg00018.html
Also fixed the detection of the new screen TERM values of type "screen.X" e.g. screen.xterm as well as retaining the older detection code.
> Fixes base16-shell to work from inside GNU screen, closing 141 and 142

- README.md
There are currently 2 sections with slightly different titles with
identical documentation in them for setting up the base16-shell vim
integration.
This commit removes the duplicated documentation.
> Remove duplicated Vim documentation

- profile_helper.sh
Everywhere else sets `BASE16_THEME` to the theme name without the `base16-` prefix.
Issue demonstrated by using `profile_helper.sh`. For example, upon initial load of the shell `BASE16_THEME=base16-gruvbox-dark-hard`. In the same session, setting the theme using the alias results in `BASE16_THEME=gruvbox-dark-hard`.
> Fix BASE16_THEME environment variable consistency

- profile_helper.fish
This should fix the known syntax errors in the `profile_helper.fish` file for people using the fish shell.
> fix syntax errors for `profile_helper.fish`

- colortest
Resolves #153
It requires the user to reopen their terminal to restore the old theme (or source ~/.base16_theme) but if this was done automatically the theme would only be shown for a fraction of a second.
> Source theme before displaying colours in colortest

- profile_helper.fish
There is an error on the shell initialization:
```sh
~/.config/base16-shell//profile_helper.fish (line 31): 'end' does not take arguments. Did you forget a ';'?
end for
^
from sourcing file ~/.config/base16-shell//profile_helper.fish
called on line 4 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
called during startup
source: Error while reading file '/Users/thomas/.config/base16-shell//profile_helper.fish'
```
This one liner fixes it.
Environment:
```sh
❯ fish -v
fish, version 3.0.0
```
> Fix loop function ending.

- profile_helper.sh
Had some issues using this with a user name with spaces, so I ran the `profile_helper.sh` through [shellcheck](https://github.com/koalaman/shellcheck) and discovered that some of the variables need to be quoted.
I am using Cygwin in this case however, this problem can occur with any users that have a space in their user name.
OS: Windows
Shell: zsh
Terminal: cygwin
> Quote variables to prevent word splitting

- README.md
Having had my awesome Base16 experience degrade recently - I went hunting to figure out why.  
As of [version 3.3 ](https://github.com/tmux/tmux/blob/master/CHANGES#L30) an [`allow-passthrough` option](https://github.com/tmux/tmux/blob/06869ff22fa9891c9633ce3e3efa77cac758b520/options-table.c#L805-L811) prevents the color escape sequences from working.
I tried to write this in the tone of the readme as I see it - but please feel free to close this and communicate it however you wish 🙏 (I suspect more people will encounter it)
> Mention required tmux allow-passthrough config
